- name: OS Version Fail
  fail:
    msg: "OS version not"
  when: ansible_distribution_major_version != "10" and
    ansible_distribution_major_version != "11" and
    ansible_distribution_major_version != "12"
- name: Set boot file
  shell: echo "/boot/cmdline.txt"
  register: bootfile
  when: ansible_distribution_major_version == "10" or
    ansible_distribution_major_version == "11"
- name: Set boot file
  shell: echo "/boot/firmware/cmdline.txt"
  register: bootfile
  when: ansible_distribution_major_version == "12"

- name: echo boot file
  shell: cat {{ bootfile.stdout }}
  register: bootcmd
- name: change boot file
  shell: sed -i 's/$/ cgroup_enable=cpuset systemd.unified_cgroup_hierarchy=0 cgroup_memory=1 cgroup_enable=memory/g' {{ bootfile.stdout }}
  when: "'cgroup_enable=cpuset' not in bootcmd.stdout"
