- name: apt isntall library
  apt:
    name:
      - apt-transport-https
      - libseccomp2
      - libseccomp-dev
      - btrfs-progs
      - libbtrfs-dev
  when: ansible_distribution_major_version == "10" or
    ansible_distribution_major_version == "11"
- name: apt install linux-modules-extra-raspi
  apt:
    name:
      - linux-modules-extra-raspi
