- name: Add Kubernetes keyring
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when:
    archdata.stdout == "32"

- name: Add Kubernetes keyring2
  ansible.builtin.get_url:
    url: "{{ k8s.key }}"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true
  when:
    archdata.stdout == "64"

- name: Add kubernetes repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://apt.kubernetes.io/ kubernetes-xenial main
  when:
    archdata.stdout == "32"


- name: Add kubernetes repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    - "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    - "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
  when:
    archdata.stdout == "64"


- name: read archdata
  shell: getconf LONG_BIT
  register: archdata

- name: Install k8s-app
  apt:
    name: "{{ item }}={{k8s.version}}"
  with_items:
    - kubectl
    - kubelet
    - kubeadm
  when:
    archdata.stdout == "64"

- name: Install k8s-app arm
  apt:
    name: "{{ item }}=1.26.7-00"
  with_items:
    - kubectl
    - kubelet
    - kubeadm
  when:
    archdata.stdout == "32"

- name: Apt Mark
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubectl
    - kubelet
    - kubeadm
