- name: Add docker keyring
  apt_key:
    url: "https://download.docker.com/linux/raspbian/gpg"
    state: present
- name: Add crio repositories 64arm
  apt_repository:
    # repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable"
    repo: "deb [arch=arm64] https://download.docker.com/linux/debian buster stable"
    state: present
  when:
    ansible_architecture == "aarch64"
- name: Add crio repositories arm
  apt_repository:
    repo: "deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable"
    state: present
  when:
    ansible_architecture == "armv7l"
- name: Upgrade apt repositories
  apt:
    upgrade: dist
    update_cache: yes

- name: install containerd
  apt:
    name:
      - containerd
- name: Setup Module
  template:
    src: ./templates/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    backup: false

- name: Setup Containerd kubelet
  template:
    src: ./templates/config.toml
    dest: /etc/containerd/config.toml
    backup: false
