- name: read archdata
  shell: getconf LONG_BIT
  register: archdata
- name: Add docker keyring
  apt_key:
    url: "https://download.docker.com/linux/raspbian/gpg"
    state: present
- name: Add crio repositories 64arm
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/debian buster stable"
    state: present
  when:
    ansible_architecture == "aarch64" and archdata.stdout == "64"
- name: Add crio repositories arm
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/debian buster stable"
    state: present
  when:
    ansible_architecture == "armv7l" or archdata.stdout == "32"
- name: Upgrade apt repositories
  apt:
    upgrade: dist
    update_cache: yes

- name: install containerd.io
  apt:
    name:
      - containerd.io
- name: Setup Module
  template:
    src: ./templates/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    backup: false
- name: create folder for containerd
  file:
    path: "/etc/containerd"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"
- name: Setup Containerd kubelet
  shell: containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/'| sudo tee /etc/containerd/config.toml
# - name: Setup Containerd kubelet
#   template:
#     src: ./templates/config.toml
#     dest: /etc/containerd/config.toml
#     backup: false
